# Generated by Django 4.2.15 on 2024-09-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
