# Generated by Django 4.2.15 on 2024-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarrillo'), ('purple', 'Morado'), ('orange', 'Naranja')], default='red', max_length=20),
        ),
    ]
