# Generated by Django 4.2.15 on 2024-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coordinate_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='coordinate_y',
            field=models.IntegerField(default=1),
        ),
    ]
