# Generated by Django 4.2.15 on 2024-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_player_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='turn',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
    ]
