# Generated by Django 4.2.15 on 2024-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0009_alter_player_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='actual_turn',
            field=models.BooleanField(default=False),
        ),
    ]
