# Generated by Django 4.2.15 on 2024-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0010_player_actual_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='actual_turn',
        ),
        migrations.AddField(
            model_name='game',
            name='actual_turn',
            field=models.IntegerField(default=0),
        ),
    ]
