# Generated by Django 4.2.15 on 2024-09-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0011_remove_player_actual_turn_game_actual_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
