# Generated by Django 4.2.15 on 2024-09-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0012_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winer',
            field=models.BooleanField(default=False),
        ),
    ]
