# Generated by Django 4.2.15 on 2024-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0014_board_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coordinate_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='coordinate_y',
            field=models.IntegerField(default=0),
        ),
    ]
